# Generated by Django 4.2.17 on 2025-03-23 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add_school', '0004_etablissement_ajoute_par'),
        ('CamerSchool', '0002_remove_avis_views_suject_avis_views_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avis_views',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='add_school.etablissement'),
        ),
    ]
