# Generated by Django 4.2.17 on 2025-02-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=100)),
                ('departement', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('public', 'Public'), ('privé', 'Privé')], max_length=50)),
                ('categories', models.CharField(choices=[('primaire', 'Primaire'), ('secondaire', 'Secondaire')], max_length=50)),
                ('adresse', models.TextField()),
                ('image_profil', models.ImageField(blank=True, null=True, upload_to='etablissements/')),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse_facebook', models.URLField(blank=True, null=True)),
                ('adresse_whatsapp', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
