# Generated by Django 4.2.17 on 2025-02-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_school',
            name='image_profil',
            field=models.ImageField(blank=True, default='etablissements/default_image.png', null=True, upload_to='etablissements/'),
        ),
    ]
