# Generated by Django 4.2.17 on 2025-03-08 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add_school', '0002_alter_add_school_image_profil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('departement', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(choices=[('public', 'Public'), ('privé', 'Privé')], max_length=10)),
                ('categorie', models.CharField(choices=[('primaire', 'Primaire'), ('secondaire', 'Secondaire')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('adresse', models.CharField(max_length=255)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('image_profil', models.ImageField(blank=True, null=True, upload_to='etablissements/profil/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoEtablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='etablissements/photos/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='add_school.etablissement')),
            ],
        ),
        migrations.DeleteModel(
            name='Add_School',
        ),
    ]
